# Perfil Docker
spring.datasource.url=jdbc:postgresql://postgres:5432/restaurante_bricio
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Mercado Pago
mercadopago.access.token=APP_USR-2340588140879621-040114-b213ead52ad6bcb0363d98b7ea33f909-118203676

# Unsplash
unsplash.access.key=CHANGE_ME_YOUR_UNSPLASH_KEY

# JWT
jwt.secret=chave_super_secreta_para_jwt_restaurante_bricio_2024